export const EMAIL_FIND_REQUEST = 'EMAIL_FIND_REQUEST';
export const EMAIL_FIND_SUCCESS = 'EMAIL_FIND_SUCCESS';
export const EMAIL_FIND_FAIL = 'EMAIL_FIND_FAIL';



export const VERIFY_SINGLE_EMAIL_REQUEST = 'VERIFY_SINGLE_EMAIL_REQUEST';
export const VERIFY_SINGLE_EMAIL_SUCCESS = 'VERIFY_SINGLE_EMAIL_SUCCESS';
export const VERIFY_SINGLE_EMAIL_FAIL = 'VERIFY_SINGLE_EMAIL_FAIL';

export const GET_INVALID_EMAILS_REQUEST = 'GET_INVALID_EMAILS_REQUEST';
export const GET_INVALID_EMAILS_SUCCESS = 'GET_INVALID_EMAILS_SUCCESS';
export const GET_INVALID_EMAILS_FAIL = 'GET_INVALID_EMAILS_FAIL';


export const VERIFY_BULK_EMAILS_REQUEST = 'VERIFY_BULK_EMAILS_REQUEST';
export const VERIFY_BULK_EMAILS_SUCCESS = 'VERIFY_BULK_EMAILS_SUCCESS';
export const VERIFY_BULK_EMAILS_FAIL = 'VERIFY_BULK_EMAILS_FAIL';


