export const GET_COMPANY_DATA_REQUEST = "GET_COMPANY_DATA_REQUEST";
export const GET_COMPANY_DATA_SUCCESS = "GET_COMPANY_DATA_SUCCESS";
export const GET_COMPANY_DATA_FAIL = "GET_COMPANY_DATA_FAIL";

export const GET_COMPANY_DETAIL_DATA_REQUEST =
  "GET_COMPANY_DETAIL_DATA_REQUEST";
export const GET_COMPANY_DETAIL_DATA_SUCCESS =
  "GET_COMPANY_DETAIL_DATA_SUCCESS";
export const GET_COMPANY_DETAIL_DATA_FAIL = "GET_COMPANY_DETAIL_DATA_FAIL";
