export const GET_EMPLOYEES_DETAIL_REQUEST = 'GET_EMPLOYEES_DETAIL_REQUEST';
export const GET_EMPLOYEES_DETAIL_SUCCESS = 'GET_EMPLOYEES_DETAIL_SUCCESS';
export const GET_EMPLOYEES_DETAIL_FAIL = 'GET_EMPLOYEES_DETAIL_FAIL';